Fix "undefined reference to ..sqrt.." on HIP-clang
It seems that HIP-clang doesn't calculate `sqrt(2)` in compile-time
because of __device__ sqrt(enable_if<int>) overload in HIP
causing this linking error:
test_scan_by_key.cpp:(.text.startup+0x31): undefined reference to
`_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_'.